### ISSUE TITLE
linorobot2_hardware/firmware, function destroyEntities() error.

### ISSUE THREAD

**Issue by hwacoding** [linorobot/linorobot2_hardware#14]
when I run this

cd linorobot2_hardware/firmware
pio run --target upload -e teensy40

![image](https://user-images.githubusercontent.com/105493201/176895675-4a3f6ce8-f913-40ac-bfc9-012438894863.png)
I have an error like this.
But, status was success. So, when I commend 
$ ros2 launch linorobot2_bringup bringup.launch.py
It works. And I can see a node linorobot2_base that have a /cmd_vel subscriber.
Also, commend 
$ ros2 run teleop_twist_keyboard teleop_twist_keyboard
It works. Motors are working.

But, When I quit these and reboot my jetson nano, I can see zombie nodes like /rplidar_... and /publisher.
I think it's because of destroyEntities().

So, When I command
$ ros2 launch linorobot2_bringup bringup.launch.py
again, there are no 
| Root.cpp             | create_client     | create
| SessionManager.hpp   | establish_session | session established
only I can see Root.cpp. Also, There is no linorobot2_base node. There is no /cmd_vel subscriber.

I will  use different ROS_DOMAIN_ID on each independent ROS2 system : https://docs.ros.org/en/foxy/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html
to kill my zombie nodes.
And I will try 
$ ros2 launch linorobot2_bringup bringup.launch.py
again. But I want to solve destroyEntities().

Please, help me. Thanks.

**Comment by grassjelly** [comment]
those are only warnings and will not cause any issues.
