### ISSUE TITLE
micro_ros_agent stuck at logger setup 

### ISSUE THREAD

**Issue by Hernansidris** [linorobot/linorobot2_hardware#15]
Hello

when i run this 
ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM0

![Screenshot from 2022-07-14 10-31-19](https://user-images.githubusercontent.com/109259830/178892206-681368ac-1505-4ccf-aacb-4442112d76c6.png)

there is no 
| Root.cpp | create_client | create
| SessionManager.hpp | establish_session | session established
only I can see Root.cpp.

i already reconnect the teensy and the result same

![Screenshot from 2022-07-14 10-36-03](https://user-images.githubusercontent.com/109259830/178892592-a8f0101e-8e78-41a6-ac5b-70974d422a4a.png)

i also run this 
ros2 topic list

![Screenshot from 2022-07-14 10-41-27](https://user-images.githubusercontent.com/109259830/178893341-90d938de-2a78-4979-b9de-be82b369e5b9.png)

there is no topic publish 
_example_
/imu/data
/odom/unfiltered
/parameter_events
/rosout

is there another/better solution?

**Comment by grassjelly** [comment]
hey @Hernansidris do you mind sharing what caused the problem?

**Comment by Hernansidris** [comment]
hay @grassjelly 
the problem i got is imu connection failed

this is not best solution but i just bypass imu connection in sourcode linorobot2_hardware/firmware/firmware.ino

![Screenshot from 2022-07-14 15-30-20](https://user-images.githubusercontent.com/109259830/178938558-38eb7206-5194-40c2-ae49-c47978f963a4.png)

the micro_ros agent not stuck again and imu data work
i dont know what the real problem

**Comment by shazib2t** [comment]
I know it is old post but I had the same issue and found the IMU was not correctly selected in the lino_base_config.h
