### ISSUE TITLE
Error while calibrating motor with teensy41 board

### ISSUE THREAD

**Issue by funnyrabbitvu** [linorobot/linorobot2_hardware#17]
After I upgrade platformio to latest version got these errors while building in figure below, before that I have built successfully.
Please give me any help and I appreciate that.

Regards,
Dat

![Screenshot from 2022-07-17 16-12-59](https://user-images.githubusercontent.com/48290085/179391863-23f39e88-ca23-4d4e-8cf8-855d1decc9ae.png)

**Comment by grassjelly** [comment]
hi have u resolved this?

**Comment by funnyrabbitvu** [comment]
> hi have u resolved this?

Yes, bro. I just exported wrong environment version :>.
