### ISSUE TITLE
[feature] ROS2 Rolling main, backports

### ISSUE THREAD

**Issue by atticusrussell** [linorobot/linorobot2_hardware#33]
Since the Galactic branch appears compatible with Humble, what are thoughts about having a Rolling branch as the main one (with current contents of Galactic) and automatic backports to branches for older ROS2 versions using GitHub Actions (with automatic testing)? 

I'm imagining something like what ros2_control does.

That way, it would be clear to the user if the software should work for them, and clear that it's up to date.

I could attempt to implement this if desired.

**Comment by grassjelly** [comment]
im planning deprecate foxy and galactic soon as I'm planning to maintain only one distro at a time, but if you're interested to get this up and running I'd be open to PRs. I'm using mergify bot to do this on the linorobot package to automatically backport distro branches from PRs. Thanks
