### ISSUE TITLE
No Longer Support 4WD Steering Robots?

### ISSUE THREAD

**Issue by EnderDragonEP** [linorobot/linorobot2_hardware#44]
There is no steering pin config inside the lino_base_config.h, and no codes about steer servo control in the source code. Was this removed in Lino Robot 2?

**Comment by grassjelly** [comment]
yes, Ackermann was removed on the ROS2 port

**Comment by EnderDragonEP** [comment]
> yes, Ackermann was removed on the ROS2 port

Ok, that's unfortunate. Thanks for the info!
