### ISSUE TITLE
motor driver related

### ISSUE THREAD

**Issue by raidhu** [linorobot/linorobot2_hardware#5]
hello jimenojmm,
    I'm using https://www.mouser.in/ProductDetail/DFRobot/DRI0018?qs=Zcin8yvlhnO3vbExFigI8Q%3D%3D - motor driver. which is based on bts7960 IC. 
It is two channel driver and has one PWM and one enable pin to control one motor does that support our use BTS7960_NOTOR_DRIVER https://github.com/linorobot/linorobot2_hardware/blob/6835a5e07ff0c5509ccf1ccac15870a7df2f401d/config/lino_base_config.h#L28
I'm sure that it works with two PWM pins(L_PWM and R_PWM) for both speed and direction.
also is that code for BTS DRIVER only support PWM signal?

**Comment by grassjelly** [comment]
The driver requires two pwm pins. You can check the implementation here.
