### ISSUE TITLE
Platformio install command stopped working

### ISSUE THREAD

**Issue by Russ76** [linorobot/linorobot2_hardware#61]
The included command line for installing Platformio no longer works. Did they move things in their repo?

**Comment by atticusrussell** [comment]
@Russ76 I think PlatformIO may have changed their install script's url. Give this one a try and let me know how it works for you:
```
python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py)"
```

https://docs.platformio.org/en/latest/core/installation/methods/installer-script.html

If it works, would you want to submit a PR updating the command in the README?
If not, I would also be happy to.

**Comment by atticusrussell** [comment]
@Russ76 you mind closing this issue if appropriate? Pretty sure #66 resolved this.

**Comment by Russ76** [comment]
Yes, I went to their web page and followed directions there! Thanks
