### ISSUE TITLE
Compiling errors trying to program Teensy4.0

### ISSUE THREAD

**Issue by Russ76** [linorobot/linorobot2_hardware#64]
This is on a new user set up to test issue. Ubuntu Jammy, Ros Humble, Robot computer Ryzen 7 with 16 GB RAM.
Would verbose output be helpful?

 pio run --target upload -e teensy40
Processing teensy40 (board: teensy40; platform: teensy; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/teensy/teensy40.html
PLATFORM: Teensy (4.18.0) > Teensy 4.0
HARDWARE: IMXRT1062 600MHz, 512KB RAM, 1.94MB Flash
DEBUG: Current (jlink) External (jlink)
PACKAGES: 
 - framework-arduinoteensy @ 1.158.0 (1.58) 
 - tool-teensy @ 1.158.0 (1.58) 
 - toolchain-gccarmnoneeabi-teensy @ 1.110301.0 (11.3.1)
Converting firmware.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Installing pyyaml with pip at PlatformIO environment
/home/mowbot/.platformio/penv/bin/python -m pip install pyyaml
Requirement already satisfied: pyyaml in /home/mowbot/.platformio/penv/lib/python3.10/site-packages (6.0.1)
Installing markupsafe==2.0.1 with pip at PlatformIO environment
/home/mowbot/.platformio/penv/bin/python -m pip install markupsafe==2.0.1
Requirement already satisfied: markupsafe==2.0.1 in /home/mowbot/.platformio/penv/lib/python3.10/site-packages (2.0.1)
Configuring teensy40 with transport serial
micro-ROS already built
Found 99 compatible libraries
Scanning dependencies...
Dependency Graph
|-- micro_ros_platformio @ 0.0.1+sha.35db5a9
|-- encoder
|-- imu
|-- kinematics
|-- motor
|-- odometry
|-- pid
Building in release mode
Compiling .pio/build/teensy40/src/firmware.ino.cpp.o
Archiving .pio/build/teensy40/lib2dc/libWire.a
Indexing .pio/build/teensy40/lib2dc/libWire.a
Compiling .pio/build/teensy40/lib1ce/imu/MPU9250.cpp.o
Compiling .pio/build/teensy40/lib755/kinematics/kinematics.cpp.o
Compiling .pio/build/teensy40/libbea/Servo/Servo.cpp.o
Compiling .pio/build/teensy40/lib098/odometry/odometry.cpp.o
Compiling .pio/build/teensy40/lib5c3/pid/pid.cpp.o
Compiling .pio/build/teensy40/FrameworkArduino/AudioStream.cpp.o
Compiling .pio/build/teensy40/FrameworkArduino/CrashReport.cpp.o
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:46:17: error: redefinition of 'rcl_publisher_t odom_publisher'
   46 | rcl_publisher_t odom_publisher;
      |                 ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:46:17: note: 'rcl_publisher_t odom_publisher' previously declared here
   46 | rcl_publisher_t odom_publisher;
      |                 ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:47:17: error: redefinition of 'rcl_publisher_t imu_publisher'
   47 | rcl_publisher_t imu_publisher;
      |                 ^~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:47:17: note: 'rcl_publisher_t imu_publisher' previously declared here
   47 | rcl_publisher_t imu_publisher;
      |                 ^~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:48:20: error: redefinition of 'rcl_subscription_t twist_subscriber'
   48 | rcl_subscription_t twist_subscriber;
      |                    ^~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:48:20: note: 'rcl_subscription_t twist_subscriber' previously declared here
   48 | rcl_subscription_t twist_subscriber;
      |                    ^~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:50:25: error: redefinition of 'nav_msgs__msg__Odometry odom_msg'
   50 | nav_msgs__msg__Odometry odom_msg;
      |                         ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:50:25: note: 'nav_msgs__msg__Odometry odom_msg' previously declared here
   50 | nav_msgs__msg__Odometry odom_msg;
      |                         ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:51:23: error: redefinition of 'sensor_msgs__msg__Imu imu_msg'
   51 | sensor_msgs__msg__Imu imu_msg;
      |                       ^~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:51:23: note: 'sensor_msgs__msg__Imu imu_msg' previously declared here
   51 | sensor_msgs__msg__Imu imu_msg;
      |                       ^~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:52:27: error: redefinition of 'geometry_msgs__msg__Twist twist_msg'
   52 | geometry_msgs__msg__Twist twist_msg;
      |                           ^~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:52:27: note: 'geometry_msgs__msg__Twist twist_msg' previously declared here
   52 | geometry_msgs__msg__Twist twist_msg;
      |                           ^~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:54:17: error: redefinition of 'rclc_executor_t executor'
   54 | rclc_executor_t executor;
      |                 ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:54:17: note: 'rclc_executor_t executor' previously declared here
   54 | rclc_executor_t executor;
      |                 ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:55:16: error: redefinition of 'rclc_support_t support'
   55 | rclc_support_t support;
      |                ^~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:55:16: note: 'rclc_support_t support' previously declared here
   55 | rclc_support_t support;
      |                ^~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:56:17: error: redefinition of 'rcl_allocator_t allocator'
   56 | rcl_allocator_t allocator;
      |                 ^~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:56:17: note: 'rcl_allocator_t allocator' previously declared here
   56 | rcl_allocator_t allocator;
      |                 ^~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:57:12: error: redefinition of 'rcl_node_t node'
   57 | rcl_node_t node;
      |            ^~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:57:12: note: 'rcl_node_t node' previously declared here
   57 | rcl_node_t node;
      |            ^~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:58:13: error: redefinition of 'rcl_timer_t control_timer'
   58 | rcl_timer_t control_timer;
      |             ^~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:58:13: note: 'rcl_timer_t control_timer' previously declared here
   58 | rcl_timer_t control_timer;
      |             ^~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:60:20: error: redefinition of 'long long unsigned int time_offset'
   60 | unsigned long long time_offset = 0;
      |                    ^~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:60:20: note: 'long long unsigned int time_offset' previously defined here
   60 | unsigned long long time_offset = 0;
      |                    ^~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:61:15: error: redefinition of 'long unsigned int prev_cmd_time'
   61 | unsigned long prev_cmd_time = 0;
      |               ^~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:61:15: note: 'long unsigned int prev_cmd_time' previously defined here
   61 | unsigned long prev_cmd_time = 0;
      |               ^~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:62:15: error: redefinition of 'long unsigned int prev_odom_update'
   62 | unsigned long prev_odom_update = 0;
      |               ^~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:62:15: note: 'long unsigned int prev_odom_update' previously defined here
   62 | unsigned long prev_odom_update = 0;
      |               ^~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:64:6: error: multiple definition of 'enum states'
   64 | enum states
      |      ^~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:64:6: note: previous definition here
   64 | enum states
      |      ^~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:70:3: error: conflicting declaration 'int state'
   70 | } state;
      |   ^~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:70:3: note: previous declaration as 'states state'
   70 | } state;
      |   ^~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:72:9: error: redefinition of 'Encoder motor1_encoder'
   72 | Encoder motor1_encoder(MOTOR1_ENCODER_A, MOTOR1_ENCODER_B, COUNTS_PER_REV1, MOTOR1_ENCODER_INV);
      |         ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:72:9: note: 'Encoder motor1_encoder' previously declared here
   72 | Encoder motor1_encoder(MOTOR1_ENCODER_A, MOTOR1_ENCODER_B, COUNTS_PER_REV1, MOTOR1_ENCODER_INV);
      |         ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:73:9: error: redefinition of 'Encoder motor2_encoder'
   73 | Encoder motor2_encoder(MOTOR2_ENCODER_A, MOTOR2_ENCODER_B, COUNTS_PER_REV2, MOTOR2_ENCODER_INV);
      |         ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:73:9: note: 'Encoder motor2_encoder' previously declared here
   73 | Encoder motor2_encoder(MOTOR2_ENCODER_A, MOTOR2_ENCODER_B, COUNTS_PER_REV2, MOTOR2_ENCODER_INV);
      |         ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:74:9: error: redefinition of 'Encoder motor3_encoder'
   74 | Encoder motor3_encoder(MOTOR3_ENCODER_A, MOTOR3_ENCODER_B, COUNTS_PER_REV3, MOTOR3_ENCODER_INV);
      |         ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:74:9: note: 'Encoder motor3_encoder' previously declared here
   74 | Encoder motor3_encoder(MOTOR3_ENCODER_A, MOTOR3_ENCODER_B, COUNTS_PER_REV3, MOTOR3_ENCODER_INV);
      |         ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:75:9: error: redefinition of 'Encoder motor4_encoder'
   75 | Encoder motor4_encoder(MOTOR4_ENCODER_A, MOTOR4_ENCODER_B, COUNTS_PER_REV4, MOTOR4_ENCODER_INV);
      |         ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:75:9: note: 'Encoder motor4_encoder' previously declared here
   75 | Encoder motor4_encoder(MOTOR4_ENCODER_A, MOTOR4_ENCODER_B, COUNTS_PER_REV4, MOTOR4_ENCODER_INV);
      |         ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:77:7: error: redefinition of 'Generic2 motor1_controller'
   77 | Motor motor1_controller(PWM_FREQUENCY, PWM_BITS, MOTOR1_INV, MOTOR1_PWM, MOTOR1_IN_A, MOTOR1_IN_B);
      |       ^~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:77:7: note: 'Generic2 motor1_controller' previously declared here
   77 | Motor motor1_controller(PWM_FREQUENCY, PWM_BITS, MOTOR1_INV, MOTOR1_PWM, MOTOR1_IN_A, MOTOR1_IN_B);
      |       ^~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:78:7: error: redefinition of 'Generic2 motor2_controller'
   78 | Motor motor2_controller(PWM_FREQUENCY, PWM_BITS, MOTOR2_INV, MOTOR2_PWM, MOTOR2_IN_A, MOTOR2_IN_B);
      |       ^~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:78:7: note: 'Generic2 motor2_controller' previously declared here
   78 | Motor motor2_controller(PWM_FREQUENCY, PWM_BITS, MOTOR2_INV, MOTOR2_PWM, MOTOR2_IN_A, MOTOR2_IN_B);
      |       ^~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:79:7: error: redefinition of 'Generic2 motor3_controller'
   79 | Motor motor3_controller(PWM_FREQUENCY, PWM_BITS, MOTOR3_INV, MOTOR3_PWM, MOTOR3_IN_A, MOTOR3_IN_B);
      |       ^~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:79:7: note: 'Generic2 motor3_controller' previously declared here
   79 | Motor motor3_controller(PWM_FREQUENCY, PWM_BITS, MOTOR3_INV, MOTOR3_PWM, MOTOR3_IN_A, MOTOR3_IN_B);
      |       ^~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:80:7: error: redefinition of 'Generic2 motor4_controller'
   80 | Motor motor4_controller(PWM_FREQUENCY, PWM_BITS, MOTOR4_INV, MOTOR4_PWM, MOTOR4_IN_A, MOTOR4_IN_B);
      |       ^~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:80:7: note: 'Generic2 motor4_controller' previously declared here
   80 | Motor motor4_controller(PWM_FREQUENCY, PWM_BITS, MOTOR4_INV, MOTOR4_PWM, MOTOR4_IN_A, MOTOR4_IN_B);
      |       ^~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:82:5: error: redefinition of 'PID motor1_pid'
   82 | PID motor1_pid(PWM_MIN, PWM_MAX, K_P, K_I, K_D);
      |     ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:82:5: note: 'PID motor1_pid' previously declared here
   82 | PID motor1_pid(PWM_MIN, PWM_MAX, K_P, K_I, K_D);
      |     ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:83:5: error: redefinition of 'PID motor2_pid'
   83 | PID motor2_pid(PWM_MIN, PWM_MAX, K_P, K_I, K_D);
      |     ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:83:5: note: 'PID motor2_pid' previously declared here
   83 | PID motor2_pid(PWM_MIN, PWM_MAX, K_P, K_I, K_D);
      |     ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:84:5: error: redefinition of 'PID motor3_pid'
   84 | PID motor3_pid(PWM_MIN, PWM_MAX, K_P, K_I, K_D);
      |     ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:84:5: note: 'PID motor3_pid' previously declared here
   84 | PID motor3_pid(PWM_MIN, PWM_MAX, K_P, K_I, K_D);
      |     ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:85:5: error: redefinition of 'PID motor4_pid'
   85 | PID motor4_pid(PWM_MIN, PWM_MAX, K_P, K_I, K_D);
      |     ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:85:5: note: 'PID motor4_pid' previously declared here
   85 | PID motor4_pid(PWM_MIN, PWM_MAX, K_P, K_I, K_D);
      |     ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:87:12: error: redefinition of 'Kinematics kinematics'
   87 | Kinematics kinematics(
      |            ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:87:12: note: 'Kinematics kinematics' previously declared here
   87 | Kinematics kinematics(
      |            ^~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:97:10: error: redefinition of 'Odometry odometry'
   97 | Odometry odometry;
      |          ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:97:10: note: 'Odometry odometry' previously declared here
   97 | Odometry odometry;
      |          ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:98:5: error: redefinition of 'MPU9250IMU imu'
   98 | IMU imu;
      |     ^~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:98:5: note: 'MPU9250IMU imu' previously declared here
   98 | IMU imu;
      |     ^~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:100:6: error: redefinition of 'void setup()'
  100 | void setup()
      |      ^~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:100:6: note: 'void setup()' previously defined here
  100 | void setup()
      |      ^~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:117:6: error: redefinition of 'void loop()'
  117 | void loop() {
      |      ^~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:117:6: note: 'void loop()' previously defined here
  117 | void loop() {
      |      ^~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:146:6: error: redefinition of 'void controlCallback(rcl_timer_t*, int64_t)'
  146 | void controlCallback(rcl_timer_t * timer, int64_t last_call_time)
      |      ^~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:146:6: note: 'void controlCallback(rcl_timer_t*, int64_t)' previously defined here
  146 | void controlCallback(rcl_timer_t * timer, int64_t last_call_time)
      |      ^~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:156:6: error: redefinition of 'void twistCallback(const void*)'
  156 | void twistCallback(const void * msgin)
      |      ^~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:156:6: note: 'void twistCallback(const void*)' previously defined here
  156 | void twistCallback(const void * msgin)
      |      ^~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:163:6: error: redefinition of 'bool createEntities()'
  163 | bool createEntities()
      |      ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:163:6: note: 'bool createEntities()' previously defined here
  163 | bool createEntities()
      |      ^~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:217:6: error: redefinition of 'bool destroyEntities()'
  217 | bool destroyEntities()
      |      ^~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:217:6: note: 'bool destroyEntities()' previously defined here
  217 | bool destroyEntities()
      |      ^~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:235:6: error: redefinition of 'void fullStop()'
  235 | void fullStop()
      |      ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:235:6: note: 'void fullStop()' previously defined here
  235 | void fullStop()
      |      ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:247:6: error: redefinition of 'void moveBase()'
  247 | void moveBase()
      |      ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:247:6: note: 'void moveBase()' previously defined here
  247 | void moveBase()
      |      ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:296:6: error: redefinition of 'void publishData()'
  296 | void publishData()
      |      ^~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:296:6: note: 'void publishData()' previously defined here
  296 | void publishData()
      |      ^~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:313:6: error: redefinition of 'void syncTime()'
  313 | void syncTime()
      |      ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:313:6: note: 'void syncTime()' previously defined here
  313 | void syncTime()
      |      ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:323:17: error: redefinition of 'timespec getTime()'
  323 | struct timespec getTime()
      |                 ^~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:323:17: note: 'timespec getTime()' previously defined here
  323 | struct timespec getTime()
      |                 ^~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:335:6: error: redefinition of 'void rclErrorLoop()'
  335 | void rclErrorLoop()
      |      ^~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:335:6: note: 'void rclErrorLoop()' previously defined here
  335 | void rclErrorLoop()
      |      ^~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:343:6: error: redefinition of 'void flashLED(int)'
  343 | void flashLED(int n_times)
      |      ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:343:6: note: 'void flashLED(int)' previously defined here
  343 | void flashLED(int n_times)
      |      ^~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino: In function 'bool destroyEntities()':
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:222:23: warning: ignoring return value of 'rcl_ret_t rcl_publisher_fini(rcl_publisher_t*, rcl_node_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  222 |     rcl_publisher_fini(&odom_publisher, &node);
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:223:23: warning: ignoring return value of 'rcl_ret_t rcl_publisher_fini(rcl_publisher_t*, rcl_node_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  223 |     rcl_publisher_fini(&imu_publisher, &node);
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:224:26: warning: ignoring return value of 'rcl_ret_t rcl_subscription_fini(rcl_subscription_t*, rcl_node_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  224 |     rcl_subscription_fini(&twist_subscriber, &node);
      |     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:225:18: warning: ignoring return value of 'rcl_ret_t rcl_node_fini(rcl_node_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  225 |     rcl_node_fini(&node);
      |     ~~~~~~~~~~~~~^~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware.ino:226:19: warning: ignoring return value of 'rcl_ret_t rcl_timer_fini(rcl_timer_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  226 |     rcl_timer_fini(&control_timer);
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino: In function 'bool destroyEntities()':
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:222:23: warning: ignoring return value of 'rcl_ret_t rcl_publisher_fini(rcl_publisher_t*, rcl_node_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  222 |     rcl_publisher_fini(&odom_publisher, &node);
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:223:23: warning: ignoring return value of 'rcl_ret_t rcl_publisher_fini(rcl_publisher_t*, rcl_node_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  223 |     rcl_publisher_fini(&imu_publisher, &node);
      |     ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:224:26: warning: ignoring return value of 'rcl_ret_t rcl_subscription_fini(rcl_subscription_t*, rcl_node_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  224 |     rcl_subscription_fini(&twist_subscriber, &node);
      |     ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:225:18: warning: ignoring return value of 'rcl_ret_t rcl_node_fini(rcl_node_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  225 |     rcl_node_fini(&node);
      |     ~~~~~~~~~~~~~^~~~~~~
/home/mowbot/lino2_ws/src/linorobot2_hardware/firmware/src/firmware (copy).ino:226:19: warning: ignoring return value of 'rcl_ret_t rcl_timer_fini(rcl_timer_t*)' declared with attribute 'warn_unused_result' [-Wunused-result]
  226 |     rcl_timer_fini(&control_timer);
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
*** [.pio/build/teensy40/src/firmware.ino.cpp.o] Error 1
lib/imu/MPU9250.cpp: In member function 'bool MPU9250::writeMemoryBlock(const uint8_t*, uint16_t, uint8_t, uint8_t, bool, bool)':
lib/imu/MPU9250.cpp:2999:14: warning: 'progBuffer' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2999 |     uint8_t *progBuffer;
      |              ^~~~~~~~~~
lib/imu/MPU9250.cpp:3025:23: warning: 'verifyBuffer' may be used uninitialized in this function [-Wmaybe-uninitialized]
 3025 |         if (verify && verifyBuffer) {
      |                       ^~~~~~~~~~~~
lib/imu/MPU9250.cpp: In member function 'bool MPU9250::writeDMPConfigurationSet(const uint8_t*, uint16_t, bool)':
lib/imu/MPU9250.cpp:3104:81: warning: 'progBuffer' may be used uninitialized in this function [-Wmaybe-uninitialized]
 3104 |                 if (sizeof(progBuffer) < length) progBuffer = (uint8_t *)realloc(progBuffer, length);
      |                                                                          ~~~~~~~^~~~~~~~~~~~~~~~~~~~
========================== [FAILED] Took 4.65 seconds ==========================

Environment    Status    Duration
-------------  --------  ------------
teensy40       FAILED    00:00:04.647
==================== 1 failed, 0 succeeded in 00:00:04.647 ====================
~/lino2_ws/src/linorobot2_hardware/firmware$

**Comment by grassjelly** [comment]
Could you try a fresh setup anywhere outside your ROS2 workspace?

**Comment by Russ76** [comment]
Yes, now it's working! Thanks

**Comment by grassjelly** [comment]
Great! Closing this
