### ISSUE TITLE
L298n driver to move forward and backward with teleop

### ISSUE THREAD

**Issue by manirajanvn** [linorobot/linorobot2_hardware#7]
Hello,
I m using teensy 4.0, L298N(GENERIC_2_IN_MOTOR_DRIVER ), GY-85 and rplidar. After upload firmware to teensy, was using teleop to test. when I press **_u, i, o_** wheels are rotating in forward and when I press **_m, ,(comma), .(dot)_** wheels are not rotating in backward. Just want to know is this expected or Am I missing something. Please find the attached driver image and config

Thanks
Mani

![l298n](https://user-images.githubusercontent.com/46883859/162667634-9ea4526d-c802-4099-9786-7167ca2975f6.jpg)
i
![l298n_1](https://user-images.githubusercontent.com/46883859/162667637-6c485cef-ef5e-47b7-ae3b-14332e7c3dbf.jpg)
[lino_base_config.h.txt](https://github.com/linorobot/linorobot2_hardware/files/8461144/lino_base_config.h.txt)

**Comment by grassjelly** [comment]
Hey @manirajanvn , 
 
Are the wheels not spinning backwards during calibration too or this behavior only happens with the firmware (w/ microros)?

**Comment by manirajanvn** [comment]
Hi,
Wheels are rotating forward separately for spin and sample commands during calibration.

**Comment by manirajanvn** [comment]
Hi,
This issue is resolved, have missed L298's GND to Teensy.
Thanks
