### ISSUE TITLE
Micro Ros Build fail in humble 

### ISSUE THREAD

**Issue by The-Kriz** [linorobot/linorobot2_hardware#70]
Processing teensy41 (board: teensy41; platform: teensy; framework: arduino)
--------------------------------------------------------------------------------
Platform Manager: Installing teensy
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Platform Manager: teensy@4.18.0 has been installed!
Tool Manager: Installing platformio/toolchain-gccarmnoneeabi-teensy @ ~1.110301.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: toolchain-gccarmnoneeabi-teensy@1.110301.0 has been installed!
Tool Manager: Installing platformio/framework-arduinoteensy @ ~1.158.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
Tool Manager: framework-arduinoteensy@1.158.0 has been installed!
Tool Manager: Installing platformio/tool-teensy @ <2
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%
Tool Manager: tool-teensy@1.158.0 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40502.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%
Tool Manager: tool-scons@4.40502.0 has been installed!
Library Manager: Installing git+https://github.com/micro-ROS/micro_ros_platformio
git version 2.34.1
Cloning into '/home/kriz/.platformio/.cache/tmp/pkg-installing-953lo0cq'...
remote: Enumerating objects: 67, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (52/52), done.
remote: Total 67 (delta 10), reused 31 (delta 4), pack-reused 0
Receiving objects: 100% (67/67), 125.66 KiB | 1.90 MiB/s, done.
Resolving deltas: 100% (10/10), done.
Library Manager: micro_ros_platformio@0.0.1+sha.841dc13 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/teensy/teensy41.html
PLATFORM: Teensy (4.18.0) > Teensy 4.1
HARDWARE: IMXRT1062 600MHz, 512KB RAM, 7.75MB Flash
DEBUG: Current (jlink) External (jlink)
PACKAGES: 
 - framework-arduinoteensy @ 1.158.0 (1.58) 
 - tool-teensy @ 1.158.0 (1.58) 
 - toolchain-gccarmnoneeabi-teensy @ 1.110301.0 (11.3.1)
Converting firmware.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Installing pyyaml with pip at PlatformIO environment
/usr/bin/python3 -m pip install pyyaml
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (5.4.1)
Installing markupsafe==2.0.1 with pip at PlatformIO environment
/usr/bin/python3 -m pip install markupsafe==2.0.1
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: markupsafe==2.0.1 in /usr/lib/python3/dist-packages (2.0.1)
Configuring teensy41 with transport serial
Downloading micro-ROS dev dependencies
	 - Downloaded ament_cmake
	 - Downloaded ament_lint
	 - Downloaded ament_package
	 - Downloaded googletest
	 - Downloaded ament_cmake_ros
	 - Downloaded ament_index
Building micro-ROS dev dependencies
Build dev micro-ROS environment failed: 
 [3.612s] WARNING:colcon.colcon_core.package_selection:Some selected packages are already built in one or more underlay workspaces:
	'ament_cmake' is in: /home/kriz/ros2_humble/install/ament_cmake
	'ament_cmake_ros' is in: /home/kriz/ros2_humble/install/ament_cmake_ros
	'ament_index_python' is in: /home/kriz/ros2_humble/install/ament_index_python
	'ament_cmake_cpplint' is in: /home/kriz/ros2_humble/install/ament_cmake_cpplint
	'ament_cmake_gtest' is in: /home/kriz/ros2_humble/install/ament_cmake_gtest
	'ament_cmake_lint_cmake' is in: /home/kriz/ros2_humble/install/ament_cmake_lint_cmake
	'ament_cmake_google_benchmark' is in: /home/kriz/ros2_humble/install/ament_cmake_google_benchmark
	'ament_cmake_xmllint' is in: /home/kriz/ros2_humble/install/ament_cmake_xmllint
	'domain_coordinator' is in: /home/kriz/ros2_humble/install/domain_coordinator
	'ament_lint_auto' is in: /home/kriz/ros2_humble/install/ament_lint_auto
	'ament_cmake_test' is in: /home/kriz/ros2_humble/install/ament_cmake_test
	'ament_cmake_mypy' is in: /home/kriz/ros2_humble/install/ament_cmake_mypy
	'ament_cmake_cppcheck' is in: /home/kriz/ros2_humble/install/ament_cmake_cppcheck
	'ament_cmake_core' is in: /home/kriz/ros2_humble/install/ament_cmake_core
	'ament_cmake_uncrustify' is in: /home/kriz/ros2_humble/install/ament_cmake_uncrustify
	'ament_cmake_clang_format' is in: /home/kriz/ros2_humble/install/ament_cmake_clang_format
	'ament_lint_common' is in: /home/kriz/ros2_humble/install/ament_lint_common
	'ament_cmake_gmock' is in: /home/kriz/ros2_humble/install/ament_cmake_gmock
	'ament_cmake_copyright' is in: /home/kriz/ros2_humble/install/ament_cmake_copyright
	'ament_cmake_pytest' is in: /home/kriz/ros2_humble/install/ament_cmake_pytest
	'ament_index_cpp' is in: /home/kriz/ros2_humble/install/ament_index_cpp
	'ament_copyright' is in: /home/kriz/ros2_humble/install/ament_copyright
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding ament_cmake ament_cmake_clang_format ament_cmake_copyright ament_cmake_core ament_cmake_cppcheck ament_cmake_cpplint ament_cmake_gmock ament_cmake_google_benchmark ament_cmake_gtest ament_cmake_lint_cmake ament_cmake_mypy ament_cmake_pytest ament_cmake_ros ament_cmake_test ament_cmake_uncrustify ament_cmake_xmllint ament_copyright ament_index_cpp ament_index_python ament_lint_auto ament_lint_common domain_coordinator

This may be promoted to an error in a future release of colcon-override-check.
--- stderr: gtest_vendor
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING

---
--- stderr: gmock_vendor
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING

---
--- stderr: ament_lint
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
--- stderr: ament_cppcheck
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
--- stderr: ament_pycodestyle
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
--- stderr: ament_package
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
---
--- stderr: ament_cmake_core
Traceback (most recent call last):
  File "/home/kriz/linorobot2_hardware/firmware/.pio/libdeps/teensy41/micro_ros_platformio/build/dev/src/ament_cmake/ament_cmake_core/cmake/core/package_xml_2_cmake.py", line 22, in <module>
    from catkin_pkg.package import parse_package_string
ModuleNotFoundError: No module named 'catkin_pkg'
CMake Error at cmake/core/ament_package_xml.cmake:95 (message):
  execute_process(/home/kriz/.platformio/penv/bin/python3.10
  /home/kriz/linorobot2_hardware/firmware/.pio/libdeps/teensy41/micro_ros_platformio/build/dev/src/ament_cmake/ament_cmake_core/cmake/core/package_xml_2_cmake.py
  /home/kriz/linorobot2_hardware/firmware/.pio/libdeps/teensy41/micro_ros_platformio/build/dev/src/ament_cmake/ament_cmake_core/package.xml
  /home/kriz/linorobot2_hardware/firmware/.pio/libdeps/teensy41/micro_ros_platformio/build/dev/build/ament_cmake_core/ament_cmake_core/package.cmake)
  returned error code 1
Call Stack (most recent call first):
  cmake/core/ament_package_xml.cmake:49 (_ament_package_xml)
  CMakeLists.txt:15 (ament_package_xml)

---
Failed   <<< ament_cmake_core [2.22s, exited with code 1]

========================= [FAILED] Took 120.12 seconds =========================

**Comment by The-Kriz** [comment]
issue was not with the linorobot2 hardware firmware was with the humble install, sorry for the trubble

**Comment by shazib2t** [comment]
@The-Kriz How did you solved this issue. I am having the same issue i guess
